# Generated by Django 6.0.4 on 2026-07-30 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_routing_protocols', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bgprouter',
            old_name='aspath_ignore',
            new_name='multipath_relax',
        ),
    ]
