# Generated by Django 6.0.4 on 2026-07-30 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0233_device_render_config_permission'),
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('netbox_routing_protocols', '0002_rename_multipath_relax'),
        ('users', '0016_default_ordering_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefixlist',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_prefix_lists', to='dcim.device'),
        ),
        migrations.AlterField(
            model_name='routemap',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_route_maps', to='dcim.device'),
        ),
        migrations.AddConstraint(
            model_name='prefixlist',
            constraint=models.UniqueConstraint(condition=models.Q(('device__isnull', True)), fields=('name',), name='netbox_routing_protocols_prefixlist_unique_shared_name', violation_error_message='A shared prefix list with this name already exists.'),
        ),
        migrations.AddConstraint(
            model_name='routemap',
            constraint=models.UniqueConstraint(condition=models.Q(('device__isnull', True)), fields=('name',), name='netbox_routing_protocols_routemap_unique_shared_name', violation_error_message='A shared route map with this name already exists.'),
        ),
    ]
