# Generated by Django 6.0.4 on 2026-07-30 13:07

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0233_device_render_config_permission'),
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('netbox_routing_protocols', '0003_shared_policy_objects'),
        ('users', '0016_default_ordering_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BFDProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100)),
                ('min_tx', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60000)])),
                ('min_rx', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60000)])),
                ('detect_multiplier', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('echo_mode', models.BooleanField(default=False)),
                ('echo_tx', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60000)])),
                ('echo_rx', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60000)])),
                ('passive_mode', models.BooleanField(default=False)),
                ('minimum_ttl', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(254)])),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_bfd_profiles', to='dcim.device')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'BFD Profile',
                'verbose_name_plural': 'BFD Profiles',
                'ordering': ('device', 'name'),
                'constraints': [models.UniqueConstraint(fields=('device', 'name'), name='netbox_routing_protocols_bfdprofile_unique_name', violation_error_message='A BFD profile with this name already exists on this device.'), models.UniqueConstraint(condition=models.Q(('device__isnull', True)), fields=('name',), name='netbox_routing_protocols_bfdprofile_unique_shared_name', violation_error_message='A shared BFD profile with this name already exists.')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
