# Generated by Django 6.0.4 on 2026-07-30 13:25

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0233_device_render_config_permission'),
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('netbox_routing_protocols', '0005_bfd_boolean_to_profile'),
        ('users', '0016_default_ordering_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGPCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('value', models.CharField(max_length=60)),
                ('type', models.CharField(default='standard', max_length=10)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'BGP Community',
                'verbose_name_plural': 'BGP Communities',
                'ordering': ('value',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BGPCommunityList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_community_lists', to='dcim.device')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'BGP Community List',
                'verbose_name_plural': 'BGP Community Lists',
                'ordering': ('device', 'name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BGPCommunityListRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('action', models.CharField(max_length=6)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='community_list_rules', to='netbox_routing_protocols.bgpcommunity')),
                ('community_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='netbox_routing_protocols.bgpcommunitylist')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'BGP Community List Rule',
                'verbose_name_plural': 'BGP Community List Rules',
                'ordering': ('community_list', 'sequence'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='bgpcommunity',
            constraint=models.UniqueConstraint(fields=('value',), name='netbox_routing_protocols_bgpcommunity_unique_value', violation_error_message='A BGP community with this value already exists.'),
        ),
        migrations.AddConstraint(
            model_name='bgpcommunitylist',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='netbox_routing_protocols_bgpcommunitylist_unique_name', violation_error_message='A community list with this name already exists on this device.'),
        ),
        migrations.AddConstraint(
            model_name='bgpcommunitylist',
            constraint=models.UniqueConstraint(condition=models.Q(('device__isnull', True)), fields=('name',), name='netbox_routing_protocols_bgpcommunitylist_unique_shared_name', violation_error_message='A shared community list with this name already exists.'),
        ),
        migrations.AddConstraint(
            model_name='bgpcommunitylistrule',
            constraint=models.UniqueConstraint(fields=('community_list', 'sequence'), name='netbox_routing_protocols_bgp_community_rule_unique_sequence', violation_error_message='This sequence number is already used in this community list.'),
        ),
    ]
